var acronymList = [
  {"acronym":"2-for-1","term":"Two items for the price of one","category":"Business"},
  {"acronym":"AFAIK","term":"As far as I know","category":"Messages"},
  {"acronym":"ASAP","term":"As soon as possible","category":""},
  {"acronym":"BC","term":"Because","category":"Messages"},
  {"acronym":"BOGO","term":"Buy one get one","category":"Business"},
  {"acronym":"BRB","term":"Be right back","category":"Messages"},
  {"acronym":"BTW","term":"By the way","category":"Messages"},
  {"acronym":"CRM","term":"Customer relationship management","category":"Business"},
  {"acronym":"CTA","term":"Call to action","category":"Business"},
  {"acronym":"EOD","term":"End of day","category":"Business"},
  {"acronym":"ETA","term":"Estimated time of arrival","category":"Business"},
  {"acronym":"FAQ","term":"Frequently asked questions","category":"Business"},
  {"acronym":"FF","term":"Follow Friday","category":"Business"},
  {"acronym":"FOMO","term":"Fear of missing out","category":"Business"},
  {"acronym":"FWD","term":"Forward","category":"Business"},
  {"acronym":"FYI","term":"For your information","category":"Messages"},
  {"acronym":"HTH","term":"Hope this helps","category":"Business"},
  {"acronym":"ICYMI","term":"In case you missed it","category":"Messages"},
  {"acronym":"IDK","term":"I don't know","category":"Messages"},
  {"acronym":"IMO","term":"In my opinion","category":"Messages"},
  {"acronym":"JK","term":"Just kidding","category":"Messages"},
  {"acronym":"K","term":"Okay","category":"Business"},
  {"acronym":"KPI","term":"Key performance indicator","category":"Business"},
  {"acronym":"LMK","term":"Let me know","category":"Messages"},
  {"acronym":"LOL","term":"Laugh out loud","category":"Messages"},
  {"acronym":"LTO","term":"Limited time offer","category":"Business"},
  {"acronym":"NP","term":"No problem","category":"Business"},
  {"acronym":"NVM","term":"Nevermind","category":"Messages"},
  {"acronym":"OMG","term":"Oh my God","category":"Messages"},
  {"acronym":"OTP","term":"One time password","category":"Business"},
  {"acronym":"ROFL","term":"Rolling on the floor laughing","category":"Messages"},
  {"acronym":"ROI","term":"Return on investment","category":"Business"},
  {"acronym":"RSVP","term":"Please respond","category":"Business"},
  {"acronym":"SMH","term":"Shaking my head","category":"Messages"},
  {"acronym":"SPK","term":"Speak","category":"Messages"},
  {"acronym":"SRY","term":"Sorry","category":"Messages"},
  {"acronym":"T&C","term":"Terms and conditions","category":"Business"},
  {"acronym":"TBH","term":"To be honest","category":"Messages"},
  {"acronym":"THX","term":"Thanks","category":"Messages"},
  {"acronym":"TIA","term":"Thanks in advance","category":"Business"},
  {"acronym":"TMI","term":"Too much information","category":"Messages"},
  {"acronym":"TTYL","term":"Talk to you later","category":"Messages"},
  {"acronym":"USP","term":"Unique selling proposition","category":"Business"},
  {"acronym":"VFM","term":"Value for money","category":"Business"},
  {"acronym":"VIP","term":"Very important person or customer","category":"Business"},
  {"acronym":"WBU","term":"What about you?","category":"Messages"},
  {"acronym":"Y?","term":"Why?","category":"Messages"},
  {"acronym":"YOLO","term":"You only live once","category":"Messages"},
  {"acronym":"nan","term":"Not applicable","category":"Business"},
]
var lastUpdate = "September 28, 2024";